"""The contract: hashes and drift, the PRD check, plan edits and how material they are, the
ledger and open-items bookkeeping, and the generated CLAUDE.md block (docs/DESIGN.md section 6)."""

from __future__ import annotations

import difflib
import hashlib
import os
import re
from dataclasses import dataclass, field
from pathlib import Path

from agent_bridge.config import Config
from agent_bridge.protocol import Edit, scope_tokens
from agent_bridge.statedir import atomic_write_text

BLOCK_VERSION = 1
BLOCK_BEGIN_RE = re.compile(r"<!-- agent-bridge:begin v(\d+)[^>]*-->")
BLOCK_BEGIN = f"<!-- agent-bridge:begin v{BLOCK_VERSION} (generated by agent-bridge; edits here are overwritten) -->"
BLOCK_END = "<!-- agent-bridge:end -->"

AUTONOMOUS = "AUTONOMOUS DECISION - owner to review"


def sha256_file(path: Path) -> str | None:
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except FileNotFoundError:
        return None


def rel(cfg: Config, path: Path) -> str:
    try:
        return str(path.relative_to(cfg.project.repo))
    except ValueError:
        return str(path)


def contract_hashes(cfg: Config) -> dict[str, str | None]:
    return {rel(cfg, p): sha256_file(p) for p in cfg.contract_files()}


def drifted(cfg: Config, approved: dict[str, str | None]) -> list[str]:
    current = contract_hashes(cfg)
    return sorted(path for path, digest in current.items() if approved.get(path) != digest)


# -- the PRD check

_HEADING = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
_PHASE_TITLE = re.compile(r"^phase\s+(\d+[a-z]?(?:\.\d+)?)\b", re.IGNORECASE)
_ITEM = re.compile(r"^\s*(?:[-*+]|\d+[.)])\s+\S")
_EXIT = re.compile(r"exit criteria", re.IGNORECASE)


@dataclass(frozen=True)
class Heading:
    level: int
    title: str
    line: int


def headings(text: str) -> list[Heading]:
    out, fenced = [], False
    for i, line in enumerate(text.splitlines()):
        if line.lstrip().startswith("```"):
            fenced = not fenced
            continue
        if not fenced and (m := _HEADING.match(line)):
            out.append(Heading(len(m.group(1)), m.group(2).strip(), i))
    return out


def phase_token(title: str) -> str | None:
    m = _PHASE_TITLE.match(title.strip())
    return f"phase {m.group(1).lower()}" if m else None


def lint_prd(text: str) -> list[str]:
    problems = []
    heads = headings(text)
    titles = [h.title.lower() for h in heads]
    for want, test in (
        ("Goals", lambda t: t.startswith("goals") or t == "goal"),
        ("Non-goals", lambda t: t.replace(" ", "-").startswith("non-goal")),
        ("Requirements", lambda t: t.startswith("requirements")),
        ("Results", lambda t: t.startswith("results")),
    ):
        if not any(test(t) for t in titles):
            problems.append(f"PRD: no {want} heading")
    if not re.search(r"\bR-\d+\b", text):
        problems.append("PRD: requirements are not numbered R-1, R-2, ...")
    lines = text.splitlines()
    phases = [h for h in heads if phase_token(h.title)]
    if not phases:
        problems.append('PRD: no phase headings (use "## Phase 1 - <name>")')
    for idx, h in enumerate(phases):
        end = next((x.line for x in heads if x.line > h.line and x.level <= h.level), len(lines))
        section = lines[h.line + 1 : end]
        exit_at = next((i for i, ln in enumerate(section) if _EXIT.search(ln)), None)
        if exit_at is None or not any(_ITEM.match(ln) for ln in section[exit_at + 1 :]):
            problems.append(f"PRD: {h.title!r} has no exit-criteria list")
    return problems


# -- plan edits


@dataclass
class EditResult:
    path: Path
    before: str
    after: str


class EditError(Exception):
    pass


def apply_edits_in_memory(cfg: Config, edits: list[Edit], allowed: list[Path]) -> list[EditResult]:
    """Check every edit against the current files and return the new contents; writes nothing."""
    allowed_set = {p.resolve() for p in allowed}
    contents: dict[Path, str] = {}
    originals: dict[Path, str] = {}
    errors: list[str] = []
    for edit in edits:
        path = (cfg.project.repo / edit.path).resolve()
        if path not in allowed_set:
            errors.append(f"{edit.path}: not a planning document the bridge may write")
            continue
        if path not in contents:
            try:
                originals[path] = contents[path] = path.read_text(encoding="utf-8")
            except FileNotFoundError:
                originals[path] = contents[path] = ""
        count = contents[path].count(edit.find)
        if count != 1:
            errors.append(f"{edit.path}: FIND text occurs {count} times (it must occur exactly once): {edit.find[:120]!r}")
            continue
        contents[path] = contents[path].replace(edit.find, edit.replace, 1)
    if errors:
        raise EditError("; ".join(errors))
    return [EditResult(p, originals[p], contents[p]) for p in contents]


def unified_diff(cfg: Config, results: list[EditResult]) -> str:
    out = []
    for r in results:
        name = rel(cfg, r.path)
        out.extend(
            difflib.unified_diff(
                r.before.splitlines(keepends=True), r.after.splitlines(keepends=True), fromfile=f"a/{name}", tofile=f"b/{name}"
            )
        )
    return "".join(out)


def write_results(results: list[EditResult]) -> None:
    for r in results:
        atomic_write_text(r.path, r.after)


@dataclass
class Assessment:
    material: bool
    weakens: bool
    affects: set[str] = field(default_factory=set)
    reasons: list[str] = field(default_factory=list)


_MATERIAL_SECTIONS = re.compile(r"goal|requirement|exit criteria|owner|scope|phase", re.IGNORECASE)
_NUMBER = re.compile(r"\d+(?:[.,]\d+)?")


def _section_chain(text: str, offset: int) -> list[Heading]:
    line = text[:offset].count("\n")
    chain: list[Heading] = []
    for h in headings(text):
        if h.line > line:
            break
        chain = [c for c in chain if c.level < h.level] + [h]
    return chain


def _in_exit_list(text: str, offset: int) -> bool:
    lines = text.splitlines()
    line = text[:offset].count("\n")
    for i in range(line, -1, -1):
        if _HEADING.match(lines[i]) and i != line:
            return False
        if _EXIT.search(lines[i]):
            return True
    return False


def assess(cfg: Config, edits: list[Edit], planner_material: bool | None) -> Assessment:
    """The bridge can only raise the planner's materiality, never lower it (DESIGN 6.6)."""
    result = Assessment(material=bool(planner_material), weakens=False)
    prd = cfg.project.prd.resolve()
    rules = {p.resolve() for p in cfg.project.rules}
    for edit in edits:
        path = (cfg.project.repo / edit.path).resolve()
        result.affects |= scope_tokens(edit.find + "\n" + edit.replace)
        if path in rules:
            result.material = True
            result.reasons.append(f"{edit.path}: the project rules are part of the contract")
            continue
        if path != prd:
            continue
        text = prd.read_text(encoding="utf-8") if prd.exists() else ""
        offset = text.find(edit.find)
        chain = _section_chain(text, max(offset, 0))
        for h in chain:
            if (token := phase_token(h.title)) is not None:
                result.affects.add(token)
        if any(_MATERIAL_SECTIONS.search(h.title) for h in chain):
            result.material = True
            result.reasons.append(f"{edit.path}: edits under {' > '.join(h.title for h in chain)}")
        old_numbers, new_numbers = _NUMBER.findall(edit.find), _NUMBER.findall(edit.replace)
        if old_numbers != new_numbers:
            result.material = True
            changed = [n for n in old_numbers if n not in new_numbers]
            if changed:
                result.weakens = True
                result.reasons.append(f"{edit.path}: changes or removes numbers {changed}")
        if offset >= 0 and _in_exit_list(text, offset):
            removed = [ln for ln in edit.find.splitlines() if ln.strip() and ln not in edit.replace.splitlines()]
            if removed:
                result.material = True
                result.weakens = True
                result.reasons.append(f"{edit.path}: changes or removes exit criteria")
    return result


# -- ledger and open items

_DEC = re.compile(r"^##\s+DEC-(\d+)\b", re.MULTILINE)
_OPEN = re.compile(r"^##\s+OPEN-(\d+)\b", re.MULTILINE)
_STATUS_LINE = re.compile(r"^-\s*Status:.*$", re.MULTILINE)


def _read(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return ""


def _next(pattern: re.Pattern[str], text: str) -> int:
    return max((int(m.group(1)) for m in pattern.finditer(text)), default=0) + 1


def _append(path: Path, header: str, entry: str) -> int:
    text = _read(path)
    if not text.strip():
        text = header
    if not text.endswith("\n"):
        text += "\n"
    text += "\n" + entry
    atomic_write_text(path, text)
    return text[: text.rindex(entry)].count("\n") + 1


def append_decision(path: Path, *, title: str, decided_by: str, status: str, body: str, change: str | None = None) -> tuple[str, int]:
    """A ledger entry; the bridge writes the heading, Decided by, Status and Change lines."""
    dec = f"DEC-{_next(_DEC, _read(path)):03d}"
    lines = [f"## {dec} {title}", f"- Decided by: {decided_by}", f"- Status: {status}"]
    if change:
        lines.append(f"- Change: {change}")
    entry = "\n".join(lines) + "\n\n" + body.strip() + "\n"
    line = _append(path, "# Decisions\n", entry)
    return dec, line


def set_decision_status(path: Path, dec: str, status: str) -> bool:
    text = _read(path)
    m = re.search(rf"^##\s+{re.escape(dec)}\b.*$", text, re.MULTILINE)
    if not m:
        return False
    nxt = re.search(r"^##\s", text[m.end() :], re.MULTILINE)
    end = m.end() + (nxt.start() if nxt else len(text) - m.end())
    section = text[m.end() : end]
    if _STATUS_LINE.search(section):
        section = _STATUS_LINE.sub(f"- Status: {status}", section, count=1)
    else:
        section = f"\n- Status: {status}" + section
    atomic_write_text(path, text[: m.end()] + section + text[end:])
    return True


def normalize_seeded_ledger(text: str, status: str) -> str:
    """Renumber the planner's seeded entries and set their Decided by / Status lines."""
    parts = re.split(r"(?m)^(?=##\s+DEC-\d+)", text)
    head, entries = parts[0], parts[1:]
    out = [head]
    for n, entry in enumerate(entries, 1):
        lines = entry.splitlines()
        title = re.sub(r"^##\s+DEC-\d+\s*", "", lines[0]).strip()
        rest = [ln for ln in lines[1:] if not re.match(r"^-\s*(Decided by|Status):", ln)]
        while rest and not rest[0].strip():
            rest.pop(0)
        block = [f"## DEC-{n:03d} {title}", "- Decided by: planner", f"- Status: {status}", "", *rest]
        out.append("\n".join(block).rstrip() + "\n\n")
    return "".join(out).rstrip() + "\n"


def seeded_decisions(text: str) -> list[str]:
    return [f"DEC-{int(m.group(1)):03d}" for m in _DEC.finditer(text)]


def append_open_item(path: Path, *, title: str, status: str, body: str) -> tuple[str, int]:
    item = f"OPEN-{_next(_OPEN, _read(path)):03d}"
    entry = f"## {item} {title}\n- Status: {status}\n- Recorded by: agent-bridge\n\n{body.strip()}\n"
    line = _append(path, "# Open items\n\nStatus: OPEN, OWNER-BLOCKED or RESOLVED.\n", entry)
    return item, line


def set_open_status(path: Path, item: str, status: str) -> bool:
    return set_decision_status(path, item, status)


# -- CLAUDE.md block, AGENTS.md, .gitignore


def block_text(cfg: Config) -> str:
    p = cfg.project
    push = (
        "Never push, and never add a remote."
        if cfg.git_push == "never"
        else "Push only what the supervisor asks you to push; never force-push."
    )
    return f"""{BLOCK_BEGIN}
## Running under agent-bridge

These rules come from the tool that runs this project; the project's own rules are above.

- **Messages are labelled.** `[owner]`: the owner's own words; binding. `[planner]`: plan changes and the
  first instruction. `[supervisor]`: the review of your last turn and your next instruction. `[bridge]`:
  automated notes from the tool; they state facts and never add scope.
- **Headless.** Nobody can answer an interactive prompt. Never use a question or ask-user tool. Put every
  question under `DECISIONS NEEDED:` in your end-of-turn report, do all the unblocked work you can first,
  then end the turn.
- **End-of-turn report.** What you did, with commits and command output as evidence; then
  `DECISIONS NEEDED:` (or none) and a `PROCEEDING:` line with the next concrete step.
- **Waiting.** To wait for a job or a time, end your report with one line, `WAIT FOR PID <n>`,
  `WAIT FOR FILE <path>` or `WAIT UNTIL <ISO-8601 time>`. The bridge sleeps without calling any model and
  wakes you when it is over. Never poll in a loop inside your turn. Long jobs run in the background: record
  their command, pid and log in the worklog.
- **The contract.** {rel(cfg, p.prd)} and {', '.join(rel(cfg, r) for r in p.rules)} are the approved plan.
  Never edit them, or `bridge.toml`; propose changes under `DECISIONS NEEDED:`. Requirements and phases
  the bridge lists as blocked are off limits until the owner settles them.
- **Records.** Decisions go in {rel(cfg, p.decisions)} as `## DEC-NNN <title>` with `- Decided by:` and
  `- Status:` lines; a decision you make that the supervisor approved has
  `Decided by: builder, approved by the supervisor`. Open items and OWNER-BLOCKED items go in
  {rel(cfg, p.open_items)}. Every number you report gets a row in {rel(cfg, p.results)}: id, what was
  measured, value, kind (`development` or `real`, as the PRD defines them), run id or artifact, commit.
  The bridge appends some entries itself (marked as recorded by agent-bridge); commit them with your next
  commit and never edit their status lines.
- **Honesty.** No fabricated numbers, no placeholder results, no tuning thresholds to make something pass,
  no development run presented as a real result. A failure is reported as a failure.
- **Commits.** Commit each coherent unit of work, with explicit paths, using the repo's own author. No
  `Co-Authored-By` or AI-attribution lines. Never rewrite history or force-push. {push}
{BLOCK_END}
"""


def apply_block(text: str, cfg: Config) -> str:
    block = block_text(cfg)
    start = BLOCK_BEGIN_RE.search(text)
    if start:
        end = text.find(BLOCK_END, start.end())
        if end != -1:
            return text[: start.start()] + block + text[end + len(BLOCK_END) :].lstrip("\n")
    sep = "" if not text or text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
    return text + sep + block


def block_version(text: str) -> int | None:
    m = BLOCK_BEGIN_RE.search(text)
    return int(m.group(1)) if m else None


def ensure_agents_symlink(repo: Path, rules: Path) -> str:
    agents = repo / "AGENTS.md"
    target = os.path.relpath(rules, repo)
    if agents.is_symlink():
        return "ok" if os.readlink(agents) == target else f"AGENTS.md links to {os.readlink(agents)}, not {target}"
    if agents.exists():
        return "AGENTS.md is a regular file; opencode reads it, not CLAUDE.md (left alone)"
    agents.symlink_to(target)
    return "created"


def ensure_gitignore(repo: Path) -> bool:
    path = repo / ".gitignore"
    text = _read(path)
    if any(line.strip() in (".bridge", ".bridge/", "/.bridge", "/.bridge/") for line in text.splitlines()):
        return False
    atomic_write_text(path, text + ("" if not text or text.endswith("\n") else "\n") + ".bridge/\n")
    return True
